auto: true
server: true
exclude: README.md, .gitignore
permalink: none
baseurl: 
url: http://nodedc.org
hashtag: '#nodedc'
twitter_search: ''
github_login: 'nodedc'
github_repo: 'nodedc.github.com'
github_language: 'JavaScript'
